### ISSUE TITLE
Missing lti key on client app start

### ISSUE THREAD

**Issue by miguelhughes** [Cvmcosta/ltijs-demo-client#1]
When I start the client app, I get the following error as a toaster message in the browser:
**Failed trying to retrieve custom parameters! Error: Missing lti key**

Have I missed a setup step?

I'm trying to connect to the demo server running locally on port 3000

browser console states:

> log.js:24 [HMR] Waiting for update signal from WDS...
home.js:108 Error: Missing lti key.
    at getLtik (home.js:92)
    at getInfo (home.js:104)
    at home.js:112
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushPassiveEffects (react-dom.development.js:22820)
    at performSyncWorkOnRoot (react-dom.development.js:21737)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at unbatchedUpdates (react-dom.development.js:21909)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:24757)
    at Object.render (react-dom.development.js:24840)
    at Module../src/index.js (index.js:8)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (serviceWorker.js:137)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
webpackHotDevClient.js:138 ./src/pages/home.js
  Line 113:6:  React Hook useEffect has a missing dependency: 'errorPrompt'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/pages/deeplink.js
  Line 80:6:  React Hook useEffect has a missing dependency: 'errorPrompt'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
webpackHotDevClient.js:138 ./src/pages/namesandroles.js
  Line 87:6:  React Hook useEffect has a missing dependency: 'errorPrompt'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210

I also had some errors when running npm install, not sure if that's related:

> $ npm install
> 
> > fsevents@1.2.13 install /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/jest-haste-map/node_modules/fsevents
> > node install.js
> 
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'nan'
> Require stack:
> - /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/jest-haste-map/node_modules/fsevents/[eval]
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Module.require (internal/modules/cjs/loader.js:1089:19)
>     at require (internal/modules/cjs/helpers.js:73:18)
>     at [eval]:1:1
>     at Script.runInThisContext (vm.js:131:18)
>     at Object.runInThisContext (vm.js:295:38)
>     at Object.<anonymous> ([eval]-wrapper:10:26)
>     at Module._compile (internal/modules/cjs/loader.js:1200:30)
>     at evalScript (internal/process/execution.js:98:25) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/jest-haste-map/node_modules/fsevents/[eval]'
>   ]
> }
> gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
> gyp ERR! System Darwin 18.7.0
> gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/jest-haste-map/node_modules/fsevents
> gyp ERR! node -v v14.3.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> 
> > fsevents@1.2.13 install /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/watchpack-chokidar2/node_modules/fsevents
> > node install.js
> 
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'nan'
> Require stack:
> - /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Module.require (internal/modules/cjs/loader.js:1089:19)
>     at require (internal/modules/cjs/helpers.js:73:18)
>     at [eval]:1:1
>     at Script.runInThisContext (vm.js:131:18)
>     at Object.runInThisContext (vm.js:295:38)
>     at Object.<anonymous> ([eval]-wrapper:10:26)
>     at Module._compile (internal/modules/cjs/loader.js:1200:30)
>     at evalScript (internal/process/execution.js:98:25) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]'
>   ]
> }
> gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
> gyp ERR! System Darwin 18.7.0
> gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/watchpack-chokidar2/node_modules/fsevents
> gyp ERR! node -v v14.3.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> 
> > fsevents@1.2.13 install /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/webpack-dev-server/node_modules/fsevents
> > node install.js
> 
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'nan'
> Require stack:
> - /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Module.require (internal/modules/cjs/loader.js:1089:19)
>     at require (internal/modules/cjs/helpers.js:73:18)
>     at [eval]:1:1
>     at Script.runInThisContext (vm.js:131:18)
>     at Object.runInThisContext (vm.js:295:38)
>     at Object.<anonymous> ([eval]-wrapper:10:26)
>     at Module._compile (internal/modules/cjs/loader.js:1200:30)
>     at evalScript (internal/process/execution.js:98:25) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
>   ]
> }
> gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
> gyp ERR! System Darwin 18.7.0
> gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/webpack-dev-server/node_modules/fsevents
> gyp ERR! node -v v14.3.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> 
> > core-js@2.6.11 postinstall /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/babel-runtime/node_modules/core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
> 
> The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> > https://opencollective.com/core-js 
> > https://www.patreon.com/zloirock 
> 
> Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> 
> 
> > core-js@3.6.5 postinstall /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> 
> > core-js-pure@3.6.5 postinstall /Users/miguelhughes/Sources/TopTal/Full Tilt Ahead/ltijs-demo/ltijs-demo-client-master/node_modules/core-js-pure
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> added 1948 packages from 846 contributors and audited 1948 packages in 21.301s
> 
> 65 packages are looking for funding
>   run `npm fund` for details
> 
> found 8 vulnerabilities (2 low, 6 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
>

**Comment by miguelhughes** [comment]
I was using this wrong. the server already has the client code "embedded" in it, in the public folder. there's no need to launch the client separately.

https://github.com/Cvmcosta/ltijs/issues/59#issuecomment-717214313
https://github.com/Cvmcosta/ltijs/issues/10#issuecomment-693746575
