### ISSUE TITLE
digital envelope routines::unsupported - workaround = react-scripts --openssl-legacy-provider start

### ISSUE THREAD

**Issue by rodneytamblyn** [Cvmcosta/ltijs-demo-client#19]
On npm start I am seeing following exceptions thrown.  Using node v18.12.1

From https://stackoverflow.com/questions/73144960/error-error0308010cdigital-envelope-routinesunsupported-at-new-hash-nodei used this to fix:

    "start": "react-scripts --openssl-legacy-provider start",

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/rodney/ltijs-demo-client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/rodney/ltijs-demo-client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/rodney/ltijs-demo-client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/rodney/ltijs-demo-client/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/rodney/ltijs-demo-client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/rodney/ltijs-demo-client/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by tlockhart** [comment]
I am receiving the same error.  See [link](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) for fix.
